name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Full test
      id: full-test
      uses: education/autograding-io-grader@v1
      with:
        test-name: Full test
        setup-command: ''
        command: cat ./output_submit.txt | grep -a PASS | wc -l
        input: ''
        expected-output: '11'
        comparison-method: contains
        timeout: 10
        max-score: 6
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        FULL-TEST_RESULTS: "${{steps.full-test.outputs.result}}"
      with:
        runners: full-test
